from datetime import datetime

MESSAGES = {
    "id": {
        "title_main": "--- HTTP Security Toolkit ---",
        "title_panel_info": "Informasi Tool PySec Auditor",
        "title_features": "Fokus Audit (Defensif/Edukasi)",
        "feature_http_tls": "HTTP & SSL/TLS",
        "desc_http_tls": "Memeriksa status koneksi, sertifikat, dan Cipher Suite.",
        "feature_security_headers": "Header Keamanan",
        "desc_security_headers": "Audit HSTS, CSP, XFO, dan lain-lain.",
        "feature_cookie_security": "Cookie Security",
        "desc_cookie_security": "Audit atribut Secure, HttpOnly, dan SameSite.",
        "feature_leakage": "Information Leakage",
        "desc_leakage": "Mendeteksi Header yang mengekspos detail infrastruktur.",
        "feature_policy": "Referrer/Permissions",
        "desc_policy": "Audit kebijakan kebocoran Referer dan kontrol fitur browser.",
        "feature_http_alt_svc": "HTTP/Alt-Svc",
        "desc_http_alt_svc": "Audit versi HTTP dan header koneksi alternatif.",
        "feature_path_traversal": "Path Traversal Check",
        "desc_path_traversal": "Pengujian dasar kerentanan Path Traversal di Query.",
        "usage_guide": "Usage: python run.py -u [TARGET_URL] [-o [FILE]] [-l [LANG]]",
        "starting_audit": "Sedang melakukan audit...",
        "target_info": "Target",
        "host_info": "Host",
        "version_title": "PySec Auditor: Versi 10.0 (Fitur Ekstrim)",
        "connection_title": "Koneksi",
        "status_code": "Status Koneksi: HTTP",
        "response_time": "Waktu Respons",
        "export_success": "✅ Ekspor Sukses: Hasil disimpan ke",
        "export_fail_format": "❌ Ekspor Gagal: Format file tidak didukung. Gunakan .json atau .html.",
        "export_fail_error": "❌ Ekspor Gagal: Terjadi kesalahan saat menyimpan file:",
        "error_connection": "Kesalahan Koneksi",
        "error_connect_fail": "ERROR: Tidak dapat terhubung ke",
        "error_unexpected": "Kesalahan Tak Terduga:",
        "audit_cookies_title": "Audit Atribut Keamanan Cookie",
        "audit_headers_title": "Analisis Header Keamanan Kritis",
        "audit_cors_title": "Audit CORS (Cross-Origin Resource Sharing)",
        "audit_methods_title": "Metode HTTP yang Diizinkan",
        "audit_exposure_title": "Deteksi Eksposur File/Direktori Sensitif",
        "audit_takeover_title": "Pemeriksaan Risiko Subdomain Takeover",
        "audit_caching_title": "Audit Header Caching",
        "audit_tls_info_title": "Informasi SSL/TLS",
        "audit_cipher_title": "Audit Cipher Suite TLS/SSL",
        "audit_leakage_title": "Audit Header Kebocoran Informasi",
        "audit_links_title": "Pemeriksaan Tautan Eksternal Berisiko (Tabnabbing)",
        "audit_referrer_title": "Audit Header Referrer-Policy",
        "audit_feature_title": "Audit Permissions Policy",
        "audit_http_version_title": "Audit Protokol HTTP",
        "audit_path_traversal_title": "Audit Dasar Path Traversal di Query",
        "warn_critical_header": "Header Keamanan Kritis hilang atau salah dikonfigurasi. Tinjau Rekomendasi!",
        "warn_cors_critical": "CORS miskonfigurasi memungkinkan situs jahat mengakses sumber daya Anda.",
        "warn_exposure_critical": "Ditemukan file/direktori yang terekspos. Ini adalah RISIKO KEAMANAN SERIUS!",
        "warn_takeover_risk": "Risiko takeover terjadi jika entri DNS CNAME mengarah ke sumber daya yang tidak ada.",
        "warn_leakage_header": "Header ini memberikan detail tentang teknologi yang digunakan. Sebaiknya hapus atau ubah menjadi nilai generik.",
        "warn_tabnabbing": "Tambahkan rel='noopener noreferrer' pada semua tautan eksternal yang menggunakan target='_blank' untuk mencegah Tabnabbing.",
        "warn_referrer_leak": "Terapkan 'no-referrer-when-downgrade' atau 'strict-origin-when-cross-origin' sebagai minimum.",
        "warn_permissions_missing": "Disarankan untuk menerapkan Permissions-Policy untuk membatasi fitur browser yang sensitif.",
        "warn_path_traversal": "Perubahan status/respons setelah injeksi payload Path Traversal terdeteksi. Wajib Verifikasi Manual!",
        "error_url_missing": "ERROR: Argumen -u/--url wajib. Gunakan -h untuk bantuan.",
    },
    "en": {
        "title_main": "--- HTTP Security Toolkit ---",
        "title_panel_info": "PySec Auditor Tool Information",
        "title_features": "Audit Focus (Defensive/Educational)",
        "feature_http_tls": "HTTP & SSL/TLS",
        "desc_http_tls": "Checks connection status, certificates, and Cipher Suites.",
        "feature_security_headers": "Security Headers",
        "desc_security_headers": "Audits HSTS, CSP, XFO, and others.",
        "feature_cookie_security": "Cookie Security",
        "desc_cookie_security": "Audits Secure, HttpOnly, and SameSite attributes.",
        "feature_leakage": "Information Leakage",
        "desc_leakage": "Detects Headers that expose infrastructure details.",
        "feature_policy": "Referrer/Permissions",
        "desc_policy": "Audits Referrer leakage policies and browser feature controls.",
        "feature_http_alt_svc": "HTTP/Alt-Svc",
        "desc_http_alt_svc": "Audits HTTP version and alternative connection headers.",
        "feature_path_traversal": "Path Traversal Check",
        "desc_path_traversal": "Basic test for Path Traversal vulnerability in Query.",
        "usage_guide": "Usage: python run.py -u [TARGET_URL] [-o [FILE]] [-l [LANG]]",
        "starting_audit": "Currently performing audit...",
        "target_info": "Target",
        "host_info": "Host",
        "version_title": "PySec Auditor: Version 10.0 (Extreme Features)",
        "connection_title": "Connection",
        "status_code": "Connection Status: HTTP",
        "response_time": "Response Time",
        "export_success": "✅ Export Successful: Results saved to",
        "export_fail_format": "❌ Export Failed: File format not supported. Use .json or .html.",
        "export_fail_error": "❌ Export Failed: An error occurred while saving the file:",
        "error_connection": "Connection Error",
        "error_connect_fail": "ERROR: Could not connect to",
        "error_unexpected": "Unexpected Error:",
        "audit_cookies_title": "Cookie Security Attribute Audit",
        "audit_headers_title": "Critical Security Header Analysis",
        "audit_cors_title": "CORS (Cross-Origin Resource Sharing) Audit",
        "audit_methods_title": "Allowed HTTP Methods",
        "audit_exposure_title": "Sensitive File/Directory Exposure Detection",
        "audit_takeover_title": "Subdomain Takeover Risk Check",
        "audit_caching_title": "Caching Header Audit",
        "audit_tls_info_title": "SSL/TLS Information",
        "audit_cipher_title": "TLS/SSL Cipher Suite Audit",
        "audit_leakage_title": "Information Leakage Header Audit",
        "audit_links_title": "Risky External Link Check (Tabnabbing)",
        "audit_referrer_title": "Referrer-Policy Header Audit",
        "audit_feature_title": "Permissions Policy Audit",
        "audit_http_version_title": "HTTP Protocol Audit",
        "audit_path_traversal_title": "Basic Path Traversal Audit in Query",
        "warn_critical_header": "Critical Security Headers are missing or misconfigured. Review Recommendations!",
        "warn_cors_critical": "CORS misconfiguration allows malicious sites to access your resources.",
        "warn_exposure_critical": "Exposed files/directories found. This is a SERIOUS SECURITY RISK!",
        "warn_takeover_risk": "Takeover risk occurs if a CNAME DNS entry points to an unbound resource.",
        "warn_leakage_header": "These headers expose technology details. Consider removing them or setting a generic value.",
        "warn_tabnabbing": "Add rel='noopener noreferrer' to all external links using target='_blank' to prevent Tabnabbing.",
        "warn_referrer_leak": "Implement 'no-referrer-when-downgrade' or 'strict-origin-when-cross-origin' as a minimum.",
        "warn_permissions_missing": "It is recommended to implement Permissions-Policy to restrict sensitive browser features.",
        "warn_path_traversal": "Status/response change detected after Path Traversal payload injection. Manual Verification Required!",
        "error_url_missing": "ERROR: The -u/--url argument is required. Use -h for help.",
    }
}

CURRENT_LANG = "id"

def set_language(lang_code: str):
    global CURRENT_LANG
    if lang_code in MESSAGES:
        CURRENT_LANG = lang_code
    else:
        CURRENT_LANG = "id"

def get_msg(key: str) -> str:
    return MESSAGES.get(CURRENT_LANG, MESSAGES['id']).get(key, f"MISSING_MSG[{key}]")
